# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fundacja "Polskie Termopile" - blog
tagline: Artykuły, relacje, dodatkowe materiały
description: >- # this means to ignore newlines until "baseurl:"
  Podtrzymywanie i rozpowszechnianie tradycji narodowej, 
  rozwój świadomości narodowej, obywatelskiej i kulturowej, 
  dobro, piękno, prawda, świętość.
baseurl: "/blog" # the subpath of your site, e.g. /blog
domain: "polskietermopile.pl"
url: "https://polskietermopile.pl" # the base hostname & protocol for your site, e.g. http://example.com
logo: "https://polskietermopile.pl/bg.jpg"

social:
  name: Polskie Termopile
  links:
    - https://www.facebook.com/polskietermopile/
    - https://www.instagram.com/termopilepl/
    - https://www.youtube.com/@fundacjapolskietermopile
    - https://www.tiktok.com/@polskietermopile

author:
  name: Fundacja "Polskie Termopile"

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - title: Polskie Termopile na Facebooku
      icon: facebook
      url: "https://www.facebook.com/polskietermopile/"
    - title: Polskie Termopile na Instagramie
      icon: instagram
      url: "https://www.instagram.com/termopilepl/"
    - title: Polskie Termopile na YouTube
      icon: youtube
      url: "https://www.youtube.com/@fundacjapolskietermopile"
    - title: Polskie Termopile na TikToku
      icon: tiktok
      url: "https://www.tiktok.com/@polskietermopile"
#    - title: Polskie Termopile na X
#      icon: x-twitter
#      url: "https://x.com/TermopilePL"
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#  - about.markdown
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
